version: '3.8'
services:
  invoicer-customer-service:
    image: invoicer-customer-service
    environment:
        - DatabaseConnectionString=Data Source=invoicer-db-msserver,1433;Initial Catalog=invoicerdb;Integrated Security=False;User Id=sa;Password=Abc.123456;MultipleActiveResultSets=True; TrustServerCertificate=True
        - AuthorityValue=https://microlabshl.us.auth0.com/
        - AudienceValue=https://microlabshl.us.auth0.com/api/v2/
    build: 
      context: .
      dockerfile: MicroLab.Invoicer.Customer.Api/DockerFile
    ports:
      - 32770:80
    networks:
      - invoicernetwork
    depends_on:
      - invoicer-db-msserver

  invoicer-supplier-service:
    image: invoicer-supplier-service
    environment:
        - DatabaseConnectionString=Data Source=invoicer-db-msserver,1433;Initial Catalog=invoicerdb;Integrated Security=False;User Id=sa;Password=Abc.123456;MultipleActiveResultSets=True; TrustServerCertificate=True
        - AuthorityValue=https://microlabshl.us.auth0.com/
        - AudienceValue=https://microlabshl.us.auth0.com/api/v2/
    build:
      context: .
      dockerfile: MicroLab.Invoicer.Supplier.Api/DockerFile
    ports:
      - 32771:80
    networks:
      - invoicernetwork
    depends_on:
      - invoicer-db-msserver

  invoicer-db-msserver:
    container_name: invoicer-db-msserver
    build:
        context: .
        dockerfile: ./mssql-invoicerdb.dockerfile
    ports:
        - '1433:1433' 
    networks:
        - invoicernetwork
networks:
  invoicernetwork:
    external: true
