FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MicroLab.Invoicer.Supplier.Api/MicroLab.Invoicer.Supplier.Api.csproj", "MicroLab.Invoicer.Supplier.Api/"]
RUN dotnet restore "MicroLab.Invoicer.Supplier.Api/MicroLab.Invoicer.Supplier.Api.csproj"
COPY . .
WORKDIR "/src/MicroLab.Invoicer.Supplier.Api"
RUN dotnet build "MicroLab.Invoicer.Supplier.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MicroLab.Invoicer.Supplier.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MicroLab.Invoicer.Supplier.Api.dll"]
